name: build and publish

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - run: ./gradlew build

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v2

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/distributions/simple_data_storage_server.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Compute SHA256
        id: shasum
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=sha::"$(shasum -a 256 build/distributions/simple_data_storage_server.zip | awk '{printf $1}')"

    
