name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build Project and Create ZIP
        run: ./gradlew build zipDistribution

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Automated release based on the latest commit"
          files: build/distributions/${{ github.event.repository.name }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute SHA256
        id: shasum
        run: echo "sha=$(shasum -a 256 build/distributions/${{ github.event.repository.name }}.zip | awk '{print $1}')" >> $GITHUB_ENV
