name: build and publish

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - run: ./gradlew build zipDistribution

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v2

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/distributions/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Extract version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Compute SHA256
        id: shasum
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "sha=$(shasum -a 256 build/distributions/${{ github.event.repository.name }}.zip | awk '{print $1}')" >> $GITHUB_ENV
